---
# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint

default: true

# MD013/line-length - Line length (disabled for readability in prose)
MD013: false

# MD024/no-duplicate-heading - Multiple headings with the same content
# Allow duplicate headings in different sections (e.g., tabs)
MD024:
  siblings_only: true

# MD025/single-title - Multiple top-level headings
# Prevent collisions with h1s and frontmatter titles
MD025:
  front_matter_title: ""

# MD060/table-column-style - Table column style (disabled for flexibility)
MD060: false
