# Lychee link checker configuration
# https://github.com/lycheeverse/lychee

# Maximum number of concurrent requests
max_concurrency = 50

# Request timeout in seconds
timeout = 30

# Maximum number of retries for failed requests
max_retries = 3

# Rate limit for requests (requests per second)
max_requests_per_second = 10

# User agent string
user_agent = "Mozilla/5.0 (compatible; lychee link checker)"

# Accept these status codes as valid
accept = [200, 201, 202, 203, 204, 301, 302, 303, 307, 308]

# Check internal links (links within the same domain)
skip_missing = false

# Exclude patterns (can also be in .lycheeignore)
exclude = [
  # Common patterns for example/placeholder URLs
  "example\\.com",
  "example\\.org",
  "localhost",
  "127\\.0\\.0\\.1",
  
  # GitHub edit links that may require auth
  "github\\.com/.*/edit/",
  
  # Social media that blocks bots
  "twitter\\.com",
  "x\\.com",
  "linkedin\\.com",
  
  # Dynamic or JavaScript-only content
  "^#",
  "^javascript:",
  
  # Email addresses
  "^mailto:",
  
  # Tel links
  "^tel:",
]

# Headers to send with requests (useful for APIs that require auth)
[headers]
# Add any custom headers here if needed
# "Authorization" = "Bearer token"

# Remap URLs (useful for checking staging/production URLs locally)
# Note: Uncomment and modify the example below if you need URL remapping
# [remap]
# "https://docs.infrahub.app" = "file://./docs/build"